account:
  host: "diy-accounts-api.us-w2.cloudhub.io"
  port: "80"
  basepath: "/"
  client_id: "6d9e329147164bf08a2cc4eeb075252e"
  client_secret: "B20a21B05dBb4287a7C49076D6E0d377"
  protocol: "HTTP"